config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



  scope :api do
    resources :recipes do
      resources :ingredients
    end
  end



  root to: 'home#index'

  match '*path' => 'home#index', via: :get


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe

  # def self.search(search)
  #   search.split(",").reduce{|item| where("name LIKE ?", "%#{item}%")}
  # end

  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end
  #
  # def self.search(search)
  #   search.split(", ").map do |item|
  #     puts item
  #     where("name LIKE ?", "%#{item}%")
  #   end
  # end

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients, dependent: :destroy

  # def self.search(search)
  #   where("name LIKE ?", "%#{search}%")
  # end


  after_destroy :reseed_if_no_more_recipes


  private
  def reseed_if_no_more_recipes
    if self.class.all.length == 0
      seeds = File.join(Rails.root, 'db', 'seeds.rb')
      load(seeds)
    end
  end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render file: Rails.root.join('public', 'myrecipeclient', 'index.html'), layout: false
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @recipe = Recipe.find(params[:recipe_id])
      @ingredients = Ingredient.all

      respond_to do |format|
       format.html { render :index }
       format.json { render json: @ingredients }
     end
    end

    def new
      @recipe = Recipe.find(params[:recipe_id])
      @ingredient = @recipe.ingredients.new

      respond_to do |format|
        format.html { render :new }
        format.json { render json: @ingredient}
      end
    end



    def create
      @recipe = Recipe.find(params[:recipe_id])
      @ingredient = @recipe.ingredients.new(ingredient_params)
      respond_to do |format|
        if @ingredient.save!
            format.html {redirect_to [@recipe, @ingredient], notice: 'Ingredient was successfully updated.'}
            format.json {render json: @ingredient}
          else
            format.html {render :edit}
            format.json {render json: @ingrediente.erros, status: :unprocessable_entity}
          end
        end
    end

    def show
      @recipe = Recipe.find(params[:recipe_id])
      @ingredient = Ingredient.find(params[:id])

      respond_to do |format|
       format.html { render :show }
       format.json { render json: @ingredient }
     end
    end


    def edit
      @recipe = Recipe.find(params[:recipe_id])
      @ingredient = Ingredient.find(params[:id])
    end

    def update
      @recipe = Recipe.find(params[:recipe_id])
      @ingredient = Ingredient.find(params[:id])
      respond_to do |format|
        if @ingredient.update!(ingredient_params)
    format.html {redirect_to [@recipe, @ingredient], notice: 'Ingredient was successfully updated.'}
    format.json {render json: @ingredient}
  else
    format.html {render :edit}
    format.json {render json: @ingredient.erros, status: :unprocessable_entity}
    end
  end
end

def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy
    redirect_to @recipe
  end


    private
    def ingredient_params
      params.require(:ingredient).permit(:name, :type)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

def index

  if params[:search]
    @recipes = []
    @ingredients = Ingredient.search(params[:search])
    @ingredients.each do |ingredient|
    @recipes.push(Recipe.find_by(name: ingredient.recipe.name))
    end
  else
    @ingredients = Ingredient.all
    @recipes = Recipe.all
  end



  # render json: @recipes
  @recipes = @recipes.uniq.sort_by{|recipe| recipe["name"]}
  respond_to do |format|
   format.html { render :index }
   format.json { render json: @recipes, include: [:ingredients]}
  end
end

def new
  @recipe = Recipe.new
end

def create
  @recipe = Recipe.new(recipe_params)

  respond_to do |format|
    if @recipe.save!
      format.html { redirect_to @recipe, notice: 'Recipe was successfully created.'}
      format.json { render json: @recipe, status: :created, location: @recipe}
    else
      format.html { render :new }
      format.json { render json: @recipe.errors, status: :unprocessable_entity }
    end
  end
end

def show
  @recipe = Recipe.find(params[:id])

  respond_to do |format|
   format.html { render :show }
   format.json { render json: @recipe, include: [:ingredients] }
 end
end

def edit
  @recipe = Recipe.find(params[:id])
end

def update
  @recipe = Recipe.find(params[:id])
  @recipe.update(recipe_params)

  redirect_to recipes_path
end

def destroy
  @recipe = Recipe.find(params[:id])
  @recipe.destroy

  redirect_to "/recipes"
end

private
def recipe_params
  params.require(:recipe).permit(:name, :directions, :photo_url, :search)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ingredients/edit.html.erb
<h1>Edit Ingredient</h1>

<%= form_for [@recipe, @ingredient] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :type %>
  <%= f.text_field :type %>

  <%= f.submit %>type
<% end %>

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>
<% @ingredients.each do |ingredient| %>
  <div>
    <%= ingredient.name %>
    <%= ingredient.recipe.name %>
<% end %>
  </div>

app/views/ingredients/new.html.erb
<h2>New Ingredients</h2>


<%= form_for [@recipe, @ingredient] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/ingredients/show.html.erb
<%= link_to "Recipe", recipe_path(@recipe) %>
<%= link_to "New", new_recipe_ingredient_path %>
<%= link_to "Delete Ingredient", recipe_ingredient_path(@ingredient), method: :delete %>

<h1><%= @ingredient.name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrecipe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/edit.html.erb
<h2>Edit Recipe</h2>

<%= form_for @recipe do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :directions %>
  <%= f.text_field :directions %>

  <%= f.label :photo_url %>
  <%= f.text_field :photo_url %>

  <%= f.submit "Update" %>
<% end %>

app/views/recipes/index.html.erb
<%= link_to "New", new_recipe_path %>

<%= form_tag(recipes_path, :method => 'get') do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search"%>
  </p>
<% end %>

<h1>The Recipes</h1>
<% @recipes.each do |recipe| %>
  <div class="recipe">
    <h2><%= link_to recipe.name, recipe %></h2>
      <%= recipe.photo_url %>
    <img src="<%= recipe.photo_url %>"/>
  </div>
<% end %>

app/views/recipes/new.html.erb
<h2>New Recipe</h2>


<%= form_for @recipe do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :directions %>
  <%= f.text_field :directions %>

  <%= f.label :photo_url %>
  <%= f.text_field :photo_url %>

  <%= f.submit "Create" %>
<% end %>

app/views/recipes/show.html.erb
<%= link_to "Recipes", recipes_path %>
<%= link_to "Edit Recipe", edit_recipe_path %>
<%= link_to "Delete Recipe", recipe_path(@recipe), method: :delete %>
<%= link_to "New Ingredient", new_recipe_ingredient_path(@recipe) %>


<h1><%= @recipe.name %></h1>
<% @recipe.ingredients.each do |ingredient| %>
  <div class="ingredient">
    <h2><%= link_to ingredient.name, recipe_ingredient_path(@recipe, ingredient) %></h2>

  </div>
<% end %>